#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh -dict system/blockMeshDictIDDES


runApplication decomposePar -cellDist
runParallel $(getApplication)
runApplication reconstructPar

#------------------------------------------------------------------------------
