#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

#run the RANS case first
#./RANS-Allrun


#- Run the mapfields and BlockMesh
runApplication -s kOmegaIDDES blockMesh -dict ./system/blockMeshDictIDDES

# i need to remove the 100s case first,
rm -rf ./100
sed 's/"startFrom       latestTime;"/"startFrom       startTime;"' system/controlDict
runApplication mapFields ../RANSCase1/. -consistent
ed 's/"startFrom       startTime;"/"startFrom       latestTime;"' system/controlDict


#------------------------------------------------------------------------------
