#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions


runApplication blockMesh

#- Run serial
#runApplication $(getApplication)

#- Run parallel
runApplication $(getApplication)
mv ./constant/polyMesh ./constant/polyMeshRANS
runApplication -s DNS blockMesh -dict ./system/blockMeshDictDNS
runApplication mapFields . -consistent



#------------------------------------------------------------------------------
